"""Table end date changed

Revision ID: 035f6b446619
Revises: b8830d9638bf
Create Date: 2024-02-05 21:57:32.274460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035f6b446619'
down_revision = 'b8830d9638bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
