"""Date Serealize

Revision ID: 564580edbcdb
Revises: 9456a13657f2
Create Date: 2024-02-06 13:18:57.392786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564580edbcdb'
down_revision = '9456a13657f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
