"""Serializer rules

Revision ID: bdb7c703bf40
Revises: 564580edbcdb
Create Date: 2024-02-06 13:42:31.538728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb7c703bf40'
down_revision = '564580edbcdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
