"""Table validations

Revision ID: c36c258f2471
Revises: 849238e94a75
Create Date: 2024-02-06 07:28:37.938512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36c258f2471'
down_revision = '849238e94a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
